config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { registrations:'users/registrations'}
  resources :patients,except: [:show]
  resources :meetings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#route'
  get 'footer' ,to: 'contact#footer'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  belongs_to :patient

  validates :name, :length => { :minimum => 5 ,:message => "The Patient Name Must be Minimum 4 Characters" }
  validates :patient_id, presence: true
  
  validates_datetime :start_time, :after => lambda { DateTime.now }, :after_message => "Please Make the Appointment after Present Time i.e #{(DateTime.now).to_s}"
  validates_datetime :end_time, :after => :start_time
  resourcify
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  # GET /meetings
  # GET /meetings.json
  def index
    if current_user.has_role? :admin or current_user.has_role? :nurse
      @search= Meeting.search(params[:q])
      if @search.result
        @meetings=@search.result.paginate(:page => params[:page],:per_page => 5)
      else
        @meetings=Meeting.order("created_at DESC").paginate(:page => params[:page],:per_page => 5)
      end
    elsif current_user.has_role? :doctor
      @search= current_user.meetings.search(params[:q])
      if @search.result
        @meetings=@search.result.paginate(:page => params[:page],:per_page => 5)
      else
        @meetings=current_user.meetings.order("created_at DESC").paginate(:page => params[:page],:per_page => 5)
      end
  end
end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    if current_user.has_role? :admin
      @meeting = Meeting.new
    elsif current_user.has_role? :doctor
      @meeting = current_user.meetings.new
      @meeting.user_id=current_user.id
    end
    if current_user.has_role? :admin 
      @user_meeting=Meeting.all.paginate(:page => params[:page],:per_page => 8)
    elsif current_user.has_role? :doctor
      @user_meeting=current_user.meetings.all.paginate(:page => params[:page],:per_page => 8)
    end
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    if current_user.has_role? :admin
      @meeting = Meeting.new(meeting_params)  
    elsif current_user.has_role? :doctor
      @meeting = current_user.meetings.new(meeting_params)  
    end
      if @meeting.save
        redirect_to meetings_path, notice: 'Meeting was successfully created.'
      else
        redirect_to new_meeting_path,alert: @meeting.errors
      end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:name, :start_time, :end_time, :user_id, :patient_id, :user_email)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name,placeholder: "Purpose of the Appointment",class: "form-control"%>
  </div>

  <div class="form-group school-options-dropdown">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time,{},{class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time,{},class: "form-control" %>
  </div>
  <% if has_role?(:admin)%>
    <div class="form-group ">
    <%= form.label :User %>
    <%= form.grouped_collection_select( :user_id,Role.where.not(name:'nurse'),:users,:name,:id,:email,{include_blank: false}, {class: 'form-control'})%>
    </div>
  <div class="form-group">
      <%= form.label "patient-ID" %>
      <%= form.grouped_collection_select :patient_id,User.with_any_role(:admin,:doctor),:patients,:email,:id,:name,{include_blank: true},{class: 'form-control'}%>  
  </div>
  <% elsif has_role?(:doctor) %>
    <div class="form-group">
      <%= form.label "patient-ID" %>
      <%= form.collection_select :patient_id,current_user.patients.all,:id,:name,{include_black: false},{class: " form-control"}%>  
  </div>
  <% end %>
  <div class="actions">
    <%= form.submit  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<div class="container">
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>
<br>
<%= link_to 'Show All Appointments', meetings_path,class: "btn btn-default" %>
<%= link_to 'Delete', @meeting, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger btn-outline-danger " %>
</div>

app/views/meetings/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <% if has_role?(:nurse) %>
    <nav class="navbar pd-t-10">
      <div class="navbar-header">
          <%= link_to 'Show All Patients',patients_path,class: "btn btn-default" %>
      </div>
    </nav>
  <% elsif has_role?(:admin) || has_role?(:doctor) %>
    <nav class="navbar pd-t-10">
      <div class="navbar-header">
          <%= link_to 'Back',patients_path,class: "btn btn-default" %>
      </div>
      <div class="nav navbar-right">
        <%= link_to 'New Appointment',new_meeting_path,class: "btn btn-default btn-block" %>
      </div> 
    </nav> 
  <% end %>

  <% if has_role?(:admin)%>
  <h1 class="text-center">Dear Admin..All the Existing Appointments are</h1>
  <% elsif has_role?(:nurse) %>
  <h1 class="text-center">All the Existing Appointments</h1>
  <% elsif has_role?(:doctor) %>
  <h1 class="text-center">The Existing Appointments of Dr.<%= current_user.email.split('@')[0].capitalize %></h1>
  <% end %>

  <br>
  <table class="table table-hover table-striped text-center">
  <thead>
    <tr>
      <th class="col-xs-1 text-center"><%= sort_link @search, :patient_id, "Patient_ID"%></th>
      <th class="col-xs-1 text-center"><%= sort_link @search, :patient_name, "Patient_Name"%></th>
      <th class="col-xs-1 text-center"><%= sort_link @search, :name,"Appointment Purpose"%></th>
      <th class="col-xs-1 text-center">Start_time</th>
      <th class="col-xs-1 text-center">End_Time</th>
      <% if has_role?(:nurse) or has_role?(:admin)%>
        <th class="col-xs-1 text-center"><%= sort_link @search, :user_email, "Doctor Name"%></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>  
        <td><%= meeting.patient.id %></td>
        <td><%= meeting.patient.name %></td>
        <td><%= meeting.name %></td>
        <td><%= meeting.start_time %></td>
        <td><%= meeting.end_time %></td>
        <% if has_role?(:nurse) or has_role?(:admin) %>
          <td><%= meeting.user.email.split('@')[0].capitalize %></td>
        <% end %>
        <% unless has_role?(:nurse) %>
          <td width="10%" class="text-right col-xs-1">
          <%= link_to 'Edit',edit_meeting_path(meeting), class: "btn btn-default",color: "black" %>
          <%= link_to 'Delete', meeting, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger btn-outline-danger " %>
        </td>    
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<div class="text-center">
<%= will_paginate @meetings %>
</div>
<% if has_role?(:doctor) %>
  <div class="col-md-12 text-center" >
    <%= search_form_for @search do |f| %>
    <%= f.text_field :name_cont, class: 'form-control center-block',placeholder: "Search by Appointment Purpose" %>
    <%= link_to "Clear", request.path, class: "btn btn-default" %>
    <%= f.submit class: 'btn btn-primary'%>
    <% end %>
  </div>
<% elsif has_role?(:admin) || has_role?(:nurse) %>
  <div class="col-md-12 text-center" >
    <%= search_form_for @search do |f| %>
    <%= f.text_field :name_or_patient_name_or_user_email_cont, class: 'form-control center-block',placeholder: "Search by Appointment Purpose" %>
    <%= link_to "Clear", request.path, class: "btn btn-default" %>
    <%= f.submit class: 'btn btn-primary'%>
    <% end %>
</div>
  
<% end %>
<% if has_role?(:nurse) %>
<div class="container">
  <%= month_calendar events: @meetings do |date, meetings| %>
    <%= date %>
    <% meetings.each do |meeting| %>
      <div>
        <%= meeting.patient.name%> has
        <%= link_to meeting.name, meeting %> 
      </div>
    <% end %>
  </div>
<% end %>  
<% end %>

</body>
</html>

app/views/meetings/new.html.erb
<p id="notice"><%= notice %></p>

<div class="container-sm">
<div class="modal-body row">
  <div class="col-md-7">
    <h1 class="text-center">Already Existing Appointments of Dr.<%= current_user.email.split('@')[0].capitalize %></h1>
    <%= month_calendar events: @user_meeting do |date, meetings| %>
    <%= date %>
    <% meetings.each do |meeting| %>
      <div>
        <%= meeting.patient.name%> has
        <%= link_to meeting.name, meeting %> 
      </div>
    <% end %>
<% end %>
      
  </div>
  <div class="col-md-5">
    <div class="text-center">
      <h1>Enter the Details of the Meeting</h1>
      <%= render 'form', meeting: @meeting %>
      <%= link_to "Show all Appointments", meetings_path,class: "btn btn-info" %>
  </div>
  </div>
</div>
<script>
  $(document).ready(function(){
    var patients;
      patients = $('#meeting_patient_id').html();

      $('#meeting_user_id').change(function() {
        var selected_user, new_patients, users;
        users = $('#meeting_user_id').html();
        selected_user = $('#meeting_user_id option:selected');
        new_patients = $(patients).filter("optgroup[label='" + selected_user.text() + "']").html();
        return $('#meeting_patient_id').html(new_patients);
      });
    });
</script>

app/views/meetings/show.html.erb
<div class="jumbotron align-items-center">
	<div class="container" >
<p>
  <strong>Patitent_ID:</strong>
  <%= @meeting.patient.id %>
</p>
<p>
  <strong>Patitent_Name:</strong>
  <%= @meeting.patient.name %>
</p>
<p>
  <strong>Purpose:</strong>
  <%= @meeting.name %>
</p>
<p>
  <strong>Start_Time:</strong>
  <%= @meeting.start_time %>
</p>
<p>
  <strong>end_Time:</strong>
  <%= @meeting.end_time %>
</p>
<% unless current_user.has_role? :nurse %>
  <div class="container">
  <%= link_to "Edit",edit_meeting_path, class: "btn btn-primary" %>
  <%= link_to "Back",new_meeting_path, class: "btn btn-primary" %>
  </div>
<% end %>

</div>
</div>