config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { registrations:'users/registrations'}
  resources :patients,except: [:show]
  resources :meetings
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#route'
  get 'footer' ,to: 'contact#footer'
end

app/models/patient.rb
class Patient < ApplicationRecord
	ransacker :age do
  		Arel.sql("to_char(\"#{table_name}\".\"age\", '99999999')")
	end
	
	belongs_to :user
	has_many :meetings

	validates :details, presence: true
	validates :age, :inclusion => {:in => 1...60,:message => "Age Should be Between 1 to 60"}
  	validates :name, :length => { :minimum => 4 ,:message => "The Patient Name Must be Minimum 4 Characters"}
  	validates :email, format: { with: /.*@.*/ }
  	resourcify
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	before_action :authenticate_user!
	load_and_authorize_resource

	def index
		if current_user.has_role? :admin or current_user.has_role? :nurse
			@search= Patient.search(params[:q])
			if @search.result
				@patients=@search.result.paginate(:page => params[:page],:per_page => 2)
			else
				@patients=Patient.all.order("created_at DESC").paginate(:page => params[:page],:per_page => 2)			
			end
		elsif current_user.has_role? :doctor
			@search= current_user.patients.search(params[:q])
			if @search.result
				@patients=@search.result.paginate(:page => params[:page],:per_page => 8)
			else
				@patients=current_user.patients.order("created_at DESC").paginate(:page => params[:page],:per_page => 8)
			end
		end		
	end

	def new
		if current_user.has_role? :admin 
			@patient = Patient.new
			@user_patient=Patient.all.paginate(:page => params[:page],:per_page => 8)
		elsif current_user.has_role? :doctor
			@patient = current_user.patients.new
			@user_patient=current_user.patients.all.paginate(:page => params[:page],:per_page => 8)
		end
	end

	def create
		if current_user.has_role? :admin 
			@patient=Patient.new(patient_params)
		elsif current_user.has_role? :doctor
			@patient=current_user.patients.new(patient_params)
		end
      	if @patient.save
        	redirect_to patients_path, notice: 'Patient was successfully created.'
     	else
     		redirect_to new_patient_path,alert: @patient.errors
    	end
	end

	def destroy
		@patient=Patient.destroy(params[:id])
    	respond_to do |format|
      format.html { redirect_to patients_path, notice: 'Patient was successfully destroyed.' }
    	end
	end

	def edit
		@patient = Patient.find(params[:id])
	end

	def update
		@patient = Patient.find(params[:id])
		respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patients_path, notice: 'Patient was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
	end


	private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :age, :email, :address, :details ,:date,:user_id)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if @patient.errors.full_messages.any? %>
    <% @patient.errors.full_messages.each do |error_message| %>
      <%= error_message if @patient.errors.full_messages.first == error_message %> <br />
    <% end %>
  <% end %>
  
  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name,placeholder: "Name of the Patient",class: "form-control"%>
  </div>
  <div class="form-group">
    <%= form.label :age %>
    <%= form.number_field :age,placeholder: "Enter age",class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email,placeholder: "Enter Email",class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_area :address,class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :details %>
    <%= form.text_area :details,class: "form-control" %>
  </div>
  <div class="form-inline">
    <%= form.label :date %>
    <%= form.datetime_field :date,class: "form-control" %>
  </div>
  </br>
  <% if has_role?(:admin)%>
    <div class="form-group">
    <%= form.label :User %>
    <%= form.grouped_collection_select( :user_id,Role.where.not(name:'nurse'),:users,:name,:id,:email,{include_blank: false}, {class: 'form-control '})%>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="container">
	<h1>Editing the Patient Details</h1>
	<%= render 'form', patient: @patient%>
	<%= link_to 'Back', patients_path,class: "btn btn-default"%>
</div>

app/views/patients/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <% if has_role? :nurse %>
    <nav class="navbar pd-t-10">
      <div class="nav navbar-right">
            <%= link_to 'Show Meetings',meetings_path,class: "btn btn-default" %>
      </div>
    </nav> 
  <% elsif has_role?(:admin) || has_role?(:doctor) %>
  <nav class="navbar pd-t-10">
    <div class="navbar-header">
      <%= link_to 'New Patient',new_patient_path,class: "btn btn-default" %>
    </div>
    <div class="nav navbar-right">
      <div class="dropdown">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Appointments</button>
          <ul class="dropdown-menu pull-right" aria-labelledby="dropdownMenuButton">
            <li><a href="#"><%= link_to('Schedule an Appointment',new_meeting_path) %></a></li>  
            <li><a href="#"><%= link_to('View all Appointments',meetings_path) %></a></li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
  
    
    
  <% if has_role?(:admin) %>
    <h1 class="text-center">Admin :All the Existing Patients</h1>  
  <% elsif has_role?(:doctor) %>
    <h1 class="text-center">All the Patients of Dr.<%= current_user.email.split('@')[0].capitalize %></h1>
    <% elsif has_role?(:nurse) %>
    <h2 class="text-center">Welcome Nurse <%= current_user.email.split('@')[0].capitalize %> Here is the list of All Patients</h2>
  <% end %>

<table class="table table-hover table-striped text-center">
  <thead>
    <tr>
      <th class="col-xs-1 text-center"><%= sort_link @search, :id, "Patient_ID"%></th>
      <th class="col-xs-1 text-center"><%= sort_link @search, :Name, "Name"%></th>
      <th class="col-xs-1 text-center"><%= sort_link @search, :age, "Age"%></th>
      <th class="col-xs-2 text-center"><%= sort_link @search, :email, "E-mail"%></th>
      <th class="col-xs-1 text-center"><%= sort_link @search, :address, "Address"%></th>
      <th class="col-xs-2 text-center"><%= sort_link @search, :details, "Details"%></th>
      <th class="col-xs-1 text-center"><%= sort_link @search, :date, "date"%></th>
      <% if has_role?(:admin) || has_role?(:nurse) %>
        <th class="col-xs-1 text-center"><%= sort_link @search, :user_email, "Doctor Name"%></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>  
        <td><%= patient.id %></td>
        <td><%= patient.name %></td>
        <td><%= patient.age %></td>
        <td><%= patient.email %></td>
        <td><%= patient.address %></td>
        <td><%= patient.details %></td>
        <td><%= patient.date %></td>
        <% if has_role?(:nurse) || has_role?(:admin) %>  
          <td>Dr.<%= patient.user.email.split('@')[0] %></td>
        <% end %>
        <% unless has_role?(:nurse)%>
          <td width="10%" class="text-right col-xs-1">
          <%= link_to 'Edit',edit_patient_path(patient), class: "btn btn-default",color: "black" %>
          <%= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger btn-outline-danger " %>
          </td>
        <% end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
<%= will_paginate @patients %>
</div>
<% if has_role?(:admin) || has_role?(:nurse)  %>
  <div class="col-md-12 text-center">
    <%= search_form_for @search do |f| %>
    <%= f.text_field :name_or_details_or_email_or_address_or_age_or_user_email_cont, class: 'form-control center-block',placeholder: "Name/age/Email/Address/Details" %>
    <%= link_to "Clear", request.path, class: "btn btn-default" %>
    <%= f.submit class: 'btn btn-primary mg-l-3'%>
    <% end %>
</div>    
<% elsif %>
  <div class="col-md-12 text-center">
    <%= search_form_for @search do |f| %>
    <%= f.text_field :name_or_details_or_email_or_address_or_age_cont, class: 'form-control center-block',placeholder: "Name/age/Email/Address/Details" %>
    <%= link_to "Clear", request.path, class: "btn btn-default" %>
    <%= f.submit class: 'btn btn-primary mg-l-3'%>
    <% end %>
</div>  
<% end %>

</body>
</html>

app/views/patients/new.html.erb
<% if has_role?(:admin) %>
  <h3 class="text-center">Welcome Admin</h3>  
<% elsif has_role?(:doctor) %>
  <h3 class="text-center">Welcome Dr.<%= current_user.email.split('@')[0].capitalize %>  
<% end %>
</h3>
  <div class="container-sm">
<div class="modal-body row">
  <div class="col-md-7">
    <h1 class="text-center">Already Existing Patients</h1>
      <table class="table table-bordered table-hover text-center">
        <thead class="thead-dark" >
          <tr>
            <th class="text-center">Name</th>
            <th class="text-center">Age</th>
            <th class="text-center">E-Mail</th>
            <th class="text-center">Date</th>
            <% if has_role? :admin %>
            <th class="text-center">Doctor Name</th>
            <% end %>
          </tr>
        </thead>
      <tbody>
          <% @user_patient.each do |p| %>
          <tr>
              <td><%= p.name %></td>
              <td><%= p.age %></td>
              <td><%= p.email %></td>
              <td><%= p.date %></td>
              <% if has_role? :admin %>
                <td><%= p.user.email.split("@")[0] %></td>
              <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="text-center">
        <%= will_paginate @user_patient %>
      </div>
  </div>
    <div class="col-md-5">
      <h1 class="text-center">Enter the Details of the New Patient</h1>
      <div class="text-center">
        <%= render 'form', patient: @patient %>
        <%= link_to 'Back', patients_path,class: "btn btn-default" %>
      </div>
      
    </div>  
</div>
</div>  